# Descargar la imagen de ubuntu
FROM ubuntu:22.04


# Actualizar la lista de actualizaciones
RUN apt-get update

# Actulaizar la imagen
RUN apt-get upgrade -y

# Actulaizar la imagen
#RUN apt-get install python3 -y

#Copiar la carpeta a webapp
#COPY ./webapp /home/webapp

#Establecer el directorio de trabaji
#WORKDIR /home/webapp

#Instalar pip
#Run apt-get install python3-pip -y

#Instalar las librerias
#RUN pip install -r requirements.txt

#Abrir puerto 8080
#EXPOSE 8080

#Ejecutar la aplicacion web
#CMD [ "python3", "app.py" ]


#docker run -p 8080:8080 fernandosp:v1